---
title: 'Final Project Milestone #1'
author: "Daniel Pinckney"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Potential Subject: Environmental Policy
### I am considering doing a final project that analyzes the success rate of different types of environmental policy. Potentially, I would address correlations between such things as carbon taxes or cap-and-trade systems and CO2 emissions to see if they have a noticeable effect. I also have found some data that is interesting to me; a flow diagram of energy use pathways that could help in reducing our reliance on fossil fuels from Energy Literacy. Maybe a similar visualization of the sources or end use of our energy consumption would be something I would like to pursue. There is also an environmental policy stringency data set that quantifies how strict regulations are; it would be interesting to cross that with information on how successful countries have been in remaining below the Paris Climate Accord threshold.


http://energyliteracy.com/


https://knoema.com/EPS/environmental-policy-stringency-index
