---
title: 'Final Project Milestone #2'
author: "Daniel Pinckney"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1 

The Greenest Building: An Overview of Embodied Energy in the U.S. - Fatma 
Al-Alawi

I really like the topic of this project as I am passionate about energy use
and its role in building design. I found the plots to be a little simplistic 
and I think the creator could have made them more personalized for the project,
rather than just using the default colors and basic bar and dot charts. They
were a little sparse to look at. I do, however, think that some of the
interpretation is really beneficial for the viewer and I really like the final
plot which showcases demolition cost in terms of energy. I think this project
could have used more data and charts to illustrate more information and
benefited from a more tailored aesthetic.


#2

Content of Presidential Speeches - Owen Bernstein

This project has a much larger amount of data to work with and visualize. I was
impressed with how succinctly the data is presented in the plots and the text
accompanying each plot really clarifies what is happening in each of them. I 
also really like the multiple types of plots as well as the analysis of raw
numbers for speeches as well as change over time for them. Where I wish this
project did a little more was in the differentiation of the candidates in each
plot because here they are all present as one color and style. I think it could
have helped to change their individual colors to more clearly articulate their
differences. I also think they could have changed the aesthetics of the plots,
but the data is very clear and engaging. A potential issue is that the selection
of words does not fully represent all the times that a candidate references the
selected issues. Overall, I was very impressed by this project.



#github repo: https://github.com/DPinckney/environmental_policy1